### ISSUE TITLE
Process for submitting Workshops

### ISSUE THREAD

**Issue by dcaixinha** [PixelsCamp/pixels_camp_2016_talks#352]
Hey all,

I was reading [the blog post](https://blog.pixels.camp/pixels-camp-v4-0-call-for-talks-9038bfbb75b) that describes how to submit a talk. This year I'd like to submit a workshop. Is the process the same (PR to this repo etc.)? Thanks!

**Comment by carlosefr** [comment]
Yes, the process is the same. Just identify your proposal as a workshop in the extra information section.
