### ISSUE TITLE
my name is wrong :)

### ISSUE THREAD

**Issue by NeCkEr** [PixelsCamp/pixels_camp_2016_talks#93]
Hey guys,

My name is `Bruno Barreto` not `Nuno Barreto` :)

<img width="266" alt="screen shot 2016-08-29 at 22 13 37" src="https://cloud.githubusercontent.com/assets/208790/18067843/9886aef0-6e36-11e6-8fa8-5300867fd161.png">

**Comment by celso** [comment]
Fixed.
